name: Test and Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.jsonc', 'deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
      
      - name: Run tests
        run: deno task test:all
  
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package
        run: npx jsr publish
